"""Add payment_method to Transaction

Revision ID: 177447b24c30
Revises: 0b48a242c701
Create Date: 2025-07-12 23:31:28.503900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177447b24c30'
down_revision = '0b48a242c701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
