"""empty message

Revision ID: 380944ae35e2
Revises: 6c9fd3b5829c
Create Date: 2025-06-09 15:24:30.795200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380944ae35e2'
down_revision = '6c9fd3b5829c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('employment_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('employment_status')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
