"""Add account_number to User

Revision ID: 427574892173
Revises: e7aedf61216d
Create Date: 2025-06-30 12:47:44.349997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427574892173'
down_revision = 'e7aedf61216d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['account_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
