"""add beneficiary document fields

Revision ID: 47c2b38cb7d7
Revises: a71759334a1e
Create Date: 2025-07-08 03:24:39.725306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c2b38cb7d7'
down_revision = 'a71759334a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_doc_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_doc_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('relationship_doc_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.drop_column('relationship_doc_url')
        batch_op.drop_column('address_doc_url')
        batch_op.drop_column('id_doc_url')

    # ### end Alembic commands ###
