"""Add card_type column to card table and create transaction table

Revision ID: 535afc714f3e
Revises: d419306716d7
Create Date: 2025-06-28 22:38:39.159998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535afc714f3e'
down_revision = 'd419306716d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('card_type')

    # ### end Alembic commands ###
