"""Add meter_number, phone_number, generated_code, code_type to MarketTransaction

Revision ID: 57f5e19a4a6d
Revises: 8d9dda226c6b
Create Date: 2025-07-26 17:25:42.747201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f5e19a4a6d'
down_revision = '8d9dda226c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meter_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('generated_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('code_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_transaction', schema=None) as batch_op:
        batch_op.drop_column('code_type')
        batch_op.drop_column('generated_code')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('meter_number')

    # ### end Alembic commands ###
