"""Add category, tier, amount to GroupJoinRequest

Revision ID: 58e4e258d708
Revises: d57bcedda0a4
Create Date: 2025-07-03 15:33:28.095502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e4e258d708'
down_revision = 'd57bcedda0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_join_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tier', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        # batch_op.drop_constraint(batch_op.f('group_join_request_group_id_fkey'), type_='foreignkey') # <-- COMMENT OUT or REMOVE THIS LINE
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_join_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('group_join_request_group_id_fkey'), 'stokvel_group', ['group_id'], ['id'])
        batch_op.drop_column('amount')
        batch_op.drop_column('tier')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
