"""Privacy fields

Revision ID: 71777d2cd2a7
Revises: f53518385651
Create Date: 2025-06-13 10:24:01.835110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71777d2cd2a7'
down_revision = 'f53518385651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_for_personalization', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_for_analytics', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_for_third_parties', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('data_for_third_parties')
        batch_op.drop_column('data_for_analytics')
        batch_op.drop_column('data_for_personalization')

    # ### end Alembic commands ###
