"""Add KYCVerification model

Revision ID: 91cb22f774a8
Revises: 7aa1cd241600
Create Date: 2025-06-20 17:46:50.805272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cb22f774a8'
down_revision = '7aa1cd241600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('employer_name', sa.String(length=100), nullable=True),
    sa.Column('street_address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('income_source', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('branch_code', sa.String(length=10), nullable=True),
    sa.Column('id_document_path', sa.String(length=200), nullable=True),
    sa.Column('proof_of_address_path', sa.String(length=200), nullable=True),
    sa.Column('proof_of_income_path', sa.String(length=200), nullable=True),
    sa.Column('bank_statement_path', sa.String(length=200), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyc_verification')
    # ### end Alembic commands ###
