"""Add status to Beneficiary

Revision ID: 97ffb810d3cc
Revises: 66c4ec8189e2
Create Date: 2025-07-09 18:04:16.841295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ffb810d3cc'
down_revision = '66c4ec8189e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
