"""Add description to stokvel_group

Revision ID: b5aa07d546cf
Revises: be3c92164693
Create Date: 2025-07-07 19:28:53.677582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5aa07d546cf'
down_revision = 'be3c92164693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stokvel_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stokvel_group', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
