"""Add missing referral columns to user

Revision ID: c9504a63ca65
Revises: 72a47d9c6797
Create Date: 2025-06-26 16:07:26.173189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9504a63ca65'
down_revision = '72a47d9c6797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valid_referrals', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('valid_referrals')
        batch_op.drop_column('points')
        batch_op.drop_column('referral_code')

    with op.batch_alter_table('stokvel_group', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

   