"""notification settings

Revision ID: f53518385651
Revises: 3503105873f5
Create Date: 2025-06-12 22:30:03.285146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53518385651'
down_revision = '3503105873f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_announcements', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_stokvel_updates', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_marketplace_offers', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_announcements', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_stokvel_updates', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_marketplace_offers', sa.Boolean(), nullable=True))
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('sms_notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('push_marketplace_offers')
        batch_op.drop_column('push_stokvel_updates')
        batch_op.drop_column('push_announcements')
        batch_op.drop_column('email_marketplace_offers')
        batch_op.drop_column('email_stokvel_updates')
        batch_op.drop_column('email_announcements')

    # ### end Alembic commands ###
