"""Add kyc status fields to user

Revision ID: fa8b612d9a63
Revises: 8413c70599be
Create Date: 2025-06-17 11:21:45.754003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa8b612d9a63'
down_revision = '8413c70599be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id_document_path', sa.String(length=200), nullable=True),
    sa.Column('proof_of_address_path', sa.String(length=200), nullable=True),
    sa.Column('proof_of_income_path', sa.String(length=200), nullable=True),
    sa.Column('bank_statement_path', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('tax_number', sa.String(length=20), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('branch_code', sa.String(length=10), nullable=True),
    sa.Column('street_address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_session')
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_notifications', sa.Boolean(), nullable=True))
        batch_op.drop_column('push_marketplace_offers')
        batch_op.drop_column('email_announcements')
        batch_op.drop_column('push_stokvel_updates')
        batch_op.drop_column('push_announcements')
        batch_op.drop_column('email_marketplace_offers')
        batch_op.drop_column('email_stokvel_updates')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('kyc_verification_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('kyc_rejection_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('data_for_analytics')
        batch_op.drop_column('data_for_third_parties')
        batch_op.drop_column('data_for_personalization')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_for_personalization', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_for_third_parties', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_for_analytics', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('kyc_rejection_reason')
        batch_op.drop_column('kyc_verification_date')
        batch_op.drop_column('kyc_status')

    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_stokvel_updates', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_marketplace_offers', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('push_announcements', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('push_stokvel_updates', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_announcements', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('push_marketplace_offers', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('sms_notifications')
        batch_op.drop_column('email_notifications')

    op.create_table('user_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('login_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_session_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_session_pkey'))
    )
    op.drop_table('transaction')
    op.drop_table('kyc_verification')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
